// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkmlpanblbakrsreutqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rbWxwYW5ibGJha3JzcmV1dHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NDQyNTMsImV4cCI6MjA5MDAyMDI1M30.3EFo-SNyIYalxLc7X2o_-Pzle5c_G7uDnt2mdDNhx7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});